### ISSUE TITLE
Issues with Themer after Update (Maximus Issue)

### ISSUE THREAD

**Issue by blastkrieg** [feren-OS/feren-OS-Bug-Reporting#26]
- The windows frames are gone, its a serious bug.
 - When changing theme the bar loses all costumization, its very anoying will not be able to change style without losing all changes like, name of folders in drop down menu (they do not translate so I change to portuguese in quicklaunch settings), custom quicklaunch buttons and other minor costumizations of the menu.

**Comment by feren** [comment]
Ok, might've fixed it, pushing an update now, sorry, I thought that the current script cured the maximus issue, but apparently not so...

**Comment by feren** [comment]
Ok, this has been FIXED, thanks for reporting this issue, and sorry everyone for the inconvenience.

**Comment by feren** [comment]
...onto the Configuration Resetting Issue...

**Comment by blastkrieg** [comment]
The bug about the windows frames disapeared still persists after the upgrade. Also there is another issue, when you hit the shortcut for show desktop it also minimizes the clock and you cannot recover it, is it possible to make it persistent?
Great distro guys, all awesome apart from this 3 anoying bugs.

**Comment by blastkrieg** [comment]
Sorry aboyt last answer, the bug about windows frames is fixed (needed to restart and change theme and then change it back to my original).

**Comment by blastkrieg** [comment]
Hello
there is an issue with the updates:
...
Ign:49 https://sourceforge.net/projects/feren-os-repositories/files/stable
./ Translation-en_GB
Ign:50 https://sourceforge.net/projects/feren-os-repositories/files/stable
./ Packages
Ign:45 https://sourceforge.net/projects/feren-os-repositories/files/stable
./ Translation-pt_PT
Ign:46 https://sourceforge.net/projects/feren-os-repositories/files/stable
./ Translation-pt
this is just a part, it happens with all the repository and the update
takes an eternity to end...
It's very anoying
Thanks

2017-09-06 20:33 GMT+01:00 feren CEO <notifications@github.com>:

**Comment by feren** [comment]
I know about Translation*, because they're missing, but I don't know why APT still tries to connect to them, and I don't know why Packages is continually loaded by APT... :/
